image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy

cloud-deploy:
  stage: deploy
  environment:
    name: Dev
  image: alpine
  script:
    - apk add --no-cache curl
    - curl -LO $K8S_STABLE_VERSION_URL
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir ~/.kube
    - cp $KUBECONFIG ~/.kube/config
    - cat ~/.kube/config
    - kubectl cluster-info
    - kubectl apply -f k8s/files-deployment.yaml
    - kubectl apply -f k8s/users-deployment.yaml
