image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy-azure

azure:
  image: mcr.microsoft.com/azure-cli
  stage: deploy-azure
  script:
    - kubectl apply -f k8s/files-deployment.yaml
    - kubectl apply -f k8s/users-deployment.yaml




