image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy

cloud-deploy:
  stage: deploy
  environment:
    name: Dev
  image: docker-hub.informatik.haw-hamburg.de/wp-cc-clouddrop/cloudrop/deploy
  script:
    - login-cluster.sh
    # deploy!
    - kubectl version
    - kubectl apply -n default -f k8s/files-deployment.yaml
    - kubectl apply -n default -f k8s/users-deployment.yaml
