image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy

cloud-deploy:
  stage: deploy
  environment:
    name: Dev
  image: microsoft/azure-cli
  script:
    # setup kubectl
    - curl -LO $K8S_STABLE_VERSION_URL
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir ~/.kube
    - touch ~/.kube/config
    - export KUBECONFIG=$KUBECONFIG:~/.kube/config
    # connect to azure k8s
    - az login --service-principal --username $AZ_USERNAME --password $AZ_PASSWORD --tenant $AZ_TENANT_ID
    - az aks get-credentials --resource-group $AZ_RESOURCE_GROUP --name $AZ_CLUSTER_NAME
    - kubectl config use-context $AZ_CLUSTER_NAME
    - cat ~/.kube/config
    - kubectl config view
    - kubectl config current-context
    # check if working
    # - kubectl cluster-info
    # deploy!
    - kubectl apply -f k8s/files-deployment.yaml
    - kubectl apply -f k8s/users-deployment.yaml
