kind: Service
apiVersion: v1
metadata:
  name: files-svc
  labels:
    app: spring
spec:
  selector:
    app: files-svc
  ports:
  - name: web
    protocol: TCP
    port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: files-svc
spec:
  selector:
    matchLabels:
      app: files-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: files-svc
    spec:
      containers:
        - name: files-svc
          image: docker-hub.informatik.haw-hamburg.de/wp-cc-clouddrop/files-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AZURE_BLOB_CONN_STRING
              valueFrom:
                secretKeyRef:
                    name: azure-blob
                    key: conn.string
            - name: AZURE_CS_PICTURE_ANALYSIS_KEY
              valueFrom:
                secretKeyRef:
                    name: azure-cognitive-pic
                    key: subscriptionKey
            - name: AZURE_CS_PICTURE_ANALYSIS_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: azure-cognitive-pic
                    key: endpoint
            - name: AZURE_CS_TEXT_ANALYSIS_KEY
              valueFrom:
                secretKeyRef:
                    name: azure-cognitive-text
                    key: key
            - name: AZURE_CS_TEXT_ANALYSIS_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: azure-cognitive-text
                    key: endpoint
      imagePullSecrets:
      - name: regcred