kind: Service
apiVersion: v1
metadata:
  name: files-svc
  labels:
    app: spring
spec:
  selector:
    app: files-svc
  ports:
  - name: web
    protocol: TCP
    port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: files-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: files-svc
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: files-svc
    spec:
      containers:
      - image: docker-hub.informatik.haw-hamburg.de/wp-cc-clouddrop/files-service:latest
        imagePullPolicy: Always
        name: files-svc
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /app/config/cloud-storage
          name: cloud-storage-config
          readOnly: true
        env:
        - name: CLUSTER_ENV
          valueFrom:
            configMapKeyRef:
              key: deploy-env
              name: cluster-env-config
              optional: false
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
              configMapKeyRef:
                key: jsonpath
                name: cloud-storage-credential
        - name: AZURE_BLOB_CONN_STRING
          valueFrom:
            secretKeyRef:
              key: conn.string
              name: azure-blob
              optional: true
        - name: AZURE_CS_PICTURE_ANALYSIS_KEY
          valueFrom:
            secretKeyRef:
              key: subscriptionKey
              name: azure-cognitive-pic
              optional: true
        - name: AZURE_CS_PICTURE_ANALYSIS_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: endpoint
              name: azure-cognitive-pic
              optional: true
        - name: AZURE_CS_TEXT_ANALYSIS_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: azure-cognitive-text
              optional: true
        - name: AZURE_CS_TEXT_ANALYSIS_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: endpoint
              name: azure-cognitive-text
              optional: true
      imagePullSecrets:
      - name: haw-registry
      volumes:
      - name: cloud-storage-config
        secret:
          secretName: cloud-storage-config
          optional: true
status: {}
---
