kind: Service
apiVersion: v1
metadata:
  name: users-svc
  labels:
    app: golang
spec:
  selector:
    app: users-svc
  ports:
  - name: web
    protocol: TCP
    port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: users-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users-svc
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: users-svc
    spec:
      containers:
      - image: docker-hub.informatik.haw-hamburg.de/wp-cc-clouddrop/users:latest
        imagePullPolicy: Always
        name: users-svc
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /app/config
          name: azure-cosmosdb-config
          readOnly: true
      imagePullSecrets:
      - name: haw-registry
      volumes:
      - name: azure-cosmosdb-config
        secret:
          secretName: azure-cosmosdb
          optional: true
status: {}
---
