active_directory_authority_url: "https://login.microsoftonline.com/"
resource_manager_url: "https://management.azure.com/"
credentials:
  subscription_id: bf09de0b-3313-4d7b-ad36-6a4ebcec5f89
  client_id: 540243f0-3d4c-4d5e-89ee-e5da8aecd019
  client_secret: :.=De_SPtTDUjRFuwIsgUiB03p2FTef5
  tenant_id: 38d63075-6a27-4ec4-95f9-473f5ef2f1b5

targets:
  - resource: /resourceGroups/Storage/providers/Microsoft.Storage/storageAccounts/clouddropstorage
    metrics:
    - name: "UsedCapacity"
    - name: "Ingress"
    - name: "Egress"
    - name: "Availability"
  - resource: /resourceGroups/KI/providers/Microsoft.CognitiveServices/accounts/datamining
    metrics:
    - name: "SuccessfulCalls"
    - name: "TotalErrors"
    - name: "BlockedCalls"
    - name: "Latency"